RegisterNetEvent('48dev-world:setTime')
AddEventHandler('48dev-world:setTime', function(hour, minute)
    NetworkOverrideClockTime(hour, minute, 0)
end)

RegisterNetEvent('48dev-world:setWeather')
AddEventHandler('48dev-world:setWeather', function(weatherType)
    SetWeatherTypeOverTime(weatherType, 1.0)
    Citizen.Wait(1000)
    SetWeatherTypeNowPersist(weatherType)
    SetWeatherTypeNow(weatherType)
    SetWeatherTypeNowPersist(weatherType)
end)

AddEventHandler('playerSpawned', function()
    TriggerServerEvent('48dev-world:requestSync')
end)
